package mapeamento;
// Generated 11/05/2017 13:08:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Condicao generated by hbm2java
 */
@Entity
@Table(name="condicao"
    ,schema="public"
)
public class Condicao  implements java.io.Serializable {


     private int id;
     private Acidente acidente;
     private String causaAcidente;
     private String tipoAcidente;
     private String classificacaoAcidente;
     private String faseDia;
     private String sentidoVia;
     private String condMetereologica;
     private String tipoPista;
     private String tracadoVia;
     private String usoSolo;

    public Condicao() {
    }

	
    public Condicao(Acidente acidente) {
        this.acidente = acidente;
    }
    public Condicao(Acidente acidente, String causaAcidente, String tipoAcidente, String classificacaoAcidente, String faseDia, String sentidoVia, String condMetereologica, String tipoPista, String tracadoVia, String usoSolo) {
       this.acidente = acidente;
       this.causaAcidente = causaAcidente;
       this.tipoAcidente = tipoAcidente;
       this.classificacaoAcidente = classificacaoAcidente;
       this.faseDia = faseDia;
       this.sentidoVia = sentidoVia;
       this.condMetereologica = condMetereologica;
       this.tipoPista = tipoPista;
       this.tracadoVia = tracadoVia;
       this.usoSolo = usoSolo;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="acidente"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Acidente getAcidente() {
        return this.acidente;
    }
    
    public void setAcidente(Acidente acidente) {
        this.acidente = acidente;
    }

    
    @Column(name="causa_acidente", length=200)
    public String getCausaAcidente() {
        return this.causaAcidente;
    }
    
    public void setCausaAcidente(String causaAcidente) {
        this.causaAcidente = causaAcidente;
    }

    
    @Column(name="tipo_acidente", length=200)
    public String getTipoAcidente() {
        return this.tipoAcidente;
    }
    
    public void setTipoAcidente(String tipoAcidente) {
        this.tipoAcidente = tipoAcidente;
    }

    
    @Column(name="classificacao_acidente", length=200)
    public String getClassificacaoAcidente() {
        return this.classificacaoAcidente;
    }
    
    public void setClassificacaoAcidente(String classificacaoAcidente) {
        this.classificacaoAcidente = classificacaoAcidente;
    }

    
    @Column(name="fase_dia", length=200)
    public String getFaseDia() {
        return this.faseDia;
    }
    
    public void setFaseDia(String faseDia) {
        this.faseDia = faseDia;
    }

    
    @Column(name="sentido_via", length=200)
    public String getSentidoVia() {
        return this.sentidoVia;
    }
    
    public void setSentidoVia(String sentidoVia) {
        this.sentidoVia = sentidoVia;
    }

    
    @Column(name="cond_metereologica", length=200)
    public String getCondMetereologica() {
        return this.condMetereologica;
    }
    
    public void setCondMetereologica(String condMetereologica) {
        this.condMetereologica = condMetereologica;
    }

    
    @Column(name="tipo_pista", length=200)
    public String getTipoPista() {
        return this.tipoPista;
    }
    
    public void setTipoPista(String tipoPista) {
        this.tipoPista = tipoPista;
    }

    
    @Column(name="tracado_via", length=200)
    public String getTracadoVia() {
        return this.tracadoVia;
    }
    
    public void setTracadoVia(String tracadoVia) {
        this.tracadoVia = tracadoVia;
    }

    
    @Column(name="uso_solo", length=200)
    public String getUsoSolo() {
        return this.usoSolo;
    }
    
    public void setUsoSolo(String usoSolo) {
        this.usoSolo = usoSolo;
    }




}


