package mapeamento;
// Generated 24/06/2018 02:43:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Data generated by hbm2java
 */
public class Data  implements java.io.Serializable {


     private int id;
     private String diaSemana;
     private Date dataAcidente;
     private Date horario;

    public Data() {
    }

	
    public Data(int id) {
        this.id = id;
    }
    public Data(int id, String diaSemana, Date dataAcidente, Date horario) {
       this.id = id;
       this.diaSemana = diaSemana;
       this.dataAcidente = dataAcidente;
       this.horario = horario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public Date getDataAcidente() {
        return this.dataAcidente;
    }
    
    public void setDataAcidente(Date dataAcidente) {
        this.dataAcidente = dataAcidente;
    }
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }




}


