package mapeamento;
// Generated 11/05/2017 13:08:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Data generated by hbm2java
 */
@Entity
@Table(name="data"
    ,schema="public"
)
public class Data  implements java.io.Serializable {


     private int id;
     private Acidente acidente;
     private String diaSemana;
     private Date dataAcidente;
     private Integer horario;

    public Data() {
    }

	
    public Data(Acidente acidente) {
        this.acidente = acidente;
    }
    public Data(Acidente acidente, String diaSemana, Date dataAcidente, Integer horario) {
       this.acidente = acidente;
       this.diaSemana = diaSemana;
       this.dataAcidente = dataAcidente;
       this.horario = horario;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="acidente"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Acidente getAcidente() {
        return this.acidente;
    }
    
    public void setAcidente(Acidente acidente) {
        this.acidente = acidente;
    }

    
    @Column(name="dia_semana", length=15)
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_acidente", length=13)
    public Date getDataAcidente() {
        return this.dataAcidente;
    }
    
    public void setDataAcidente(Date dataAcidente) {
        this.dataAcidente = dataAcidente;
    }

    
    @Column(name="horario")
    public Integer getHorario() {
        return this.horario;
    }
    
    public void setHorario(Integer horario) {
        this.horario = horario;
    }




}


