package mapeamento;
// Generated 24/06/2018 02:43:00 by Hibernate Tools 4.3.1



/**
 * Tipoveiculo generated by hbm2java
 */
public class Tipoveiculo  implements java.io.Serializable {


     private int tvvcodigo;
     private String tvvdescricao;
     private Character tvvatualiza;
     private Character tvvrelacidente;
     private Character tvvativo;

    public Tipoveiculo() {
    }

	
    public Tipoveiculo(int tvvcodigo) {
        this.tvvcodigo = tvvcodigo;
    }
    public Tipoveiculo(int tvvcodigo, String tvvdescricao, Character tvvatualiza, Character tvvrelacidente, Character tvvativo) {
       this.tvvcodigo = tvvcodigo;
       this.tvvdescricao = tvvdescricao;
       this.tvvatualiza = tvvatualiza;
       this.tvvrelacidente = tvvrelacidente;
       this.tvvativo = tvvativo;
    }
   
    public int getTvvcodigo() {
        return this.tvvcodigo;
    }
    
    public void setTvvcodigo(int tvvcodigo) {
        this.tvvcodigo = tvvcodigo;
    }
    public String getTvvdescricao() {
        return this.tvvdescricao;
    }
    
    public void setTvvdescricao(String tvvdescricao) {
        this.tvvdescricao = tvvdescricao;
    }
    public Character getTvvatualiza() {
        return this.tvvatualiza;
    }
    
    public void setTvvatualiza(Character tvvatualiza) {
        this.tvvatualiza = tvvatualiza;
    }
    public Character getTvvrelacidente() {
        return this.tvvrelacidente;
    }
    
    public void setTvvrelacidente(Character tvvrelacidente) {
        this.tvvrelacidente = tvvrelacidente;
    }
    public Character getTvvativo() {
        return this.tvvativo;
    }
    
    public void setTvvativo(Character tvvativo) {
        this.tvvativo = tvvativo;
    }




}


