package mapeamento;
// Generated 24/06/2018 02:43:00 by Hibernate Tools 4.3.1



/**
 * Tipoenvolvido generated by hbm2java
 */
public class Tipoenvolvido  implements java.io.Serializable {


     private int ttecodigo;
     private Character tteatualiza;
     private Character tteativo;
     private String ttedescricao;

    public Tipoenvolvido() {
    }

	
    public Tipoenvolvido(int ttecodigo) {
        this.ttecodigo = ttecodigo;
    }
    public Tipoenvolvido(int ttecodigo, Character tteatualiza, Character tteativo, String ttedescricao) {
       this.ttecodigo = ttecodigo;
       this.tteatualiza = tteatualiza;
       this.tteativo = tteativo;
       this.ttedescricao = ttedescricao;
    }
   
    public int getTtecodigo() {
        return this.ttecodigo;
    }
    
    public void setTtecodigo(int ttecodigo) {
        this.ttecodigo = ttecodigo;
    }
    public Character getTteatualiza() {
        return this.tteatualiza;
    }
    
    public void setTteatualiza(Character tteatualiza) {
        this.tteatualiza = tteatualiza;
    }
    public Character getTteativo() {
        return this.tteativo;
    }
    
    public void setTteativo(Character tteativo) {
        this.tteativo = tteativo;
    }
    public String getTtedescricao() {
        return this.ttedescricao;
    }
    
    public void setTtedescricao(String ttedescricao) {
        this.ttedescricao = ttedescricao;
    }




}


