package mapeamento;
// Generated 11/05/2017 13:08:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private String codigo;
     private String nome;
     private String senha;
     private String funcao;

    public Usuario() {
    }

    public Usuario(String codigo, String nome, String senha, String funcao) {
       this.codigo = codigo;
       this.nome = nome;
       this.senha = senha;
       this.funcao = funcao;
    }
   
     @Id 

    
    @Column(name="codigo", nullable=false, length=11)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="senha", nullable=false, length=100)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="funcao", nullable=false, length=100)
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }




}


