package mapeamento1;
// Generated 25/06/2018 17:10:40 by Hibernate Tools 4.3.1



/**
 * Condicao generated by hbm2java
 */
public class Condicao  implements java.io.Serializable {


     private int id;
     private Acidente acidente;
     private String causaAcidente;
     private String tipoAcidente;
     private String classificacaoAcidente;
     private String faseDia;
     private String sentidoVia;
     private String condMetereologico;
     private String tipoPista;
     private String tracadoVia;
     private String usoSolo;

    public Condicao() {
    }

	
    public Condicao(int id) {
        this.id = id;
    }
    public Condicao(int id, Acidente acidente, String causaAcidente, String tipoAcidente, String classificacaoAcidente, String faseDia, String sentidoVia, String condMetereologico, String tipoPista, String tracadoVia, String usoSolo) {
       this.id = id;
       this.acidente = acidente;
       this.causaAcidente = causaAcidente;
       this.tipoAcidente = tipoAcidente;
       this.classificacaoAcidente = classificacaoAcidente;
       this.faseDia = faseDia;
       this.sentidoVia = sentidoVia;
       this.condMetereologico = condMetereologico;
       this.tipoPista = tipoPista;
       this.tracadoVia = tracadoVia;
       this.usoSolo = usoSolo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Acidente getAcidente() {
        return this.acidente;
    }
    
    public void setAcidente(Acidente acidente) {
        this.acidente = acidente;
    }
    public String getCausaAcidente() {
        return this.causaAcidente;
    }
    
    public void setCausaAcidente(String causaAcidente) {
        this.causaAcidente = causaAcidente;
    }
    public String getTipoAcidente() {
        return this.tipoAcidente;
    }
    
    public void setTipoAcidente(String tipoAcidente) {
        this.tipoAcidente = tipoAcidente;
    }
    public String getClassificacaoAcidente() {
        return this.classificacaoAcidente;
    }
    
    public void setClassificacaoAcidente(String classificacaoAcidente) {
        this.classificacaoAcidente = classificacaoAcidente;
    }
    public String getFaseDia() {
        return this.faseDia;
    }
    
    public void setFaseDia(String faseDia) {
        this.faseDia = faseDia;
    }
    public String getSentidoVia() {
        return this.sentidoVia;
    }
    
    public void setSentidoVia(String sentidoVia) {
        this.sentidoVia = sentidoVia;
    }
    public String getCondMetereologico() {
        return this.condMetereologico;
    }
    
    public void setCondMetereologico(String condMetereologico) {
        this.condMetereologico = condMetereologico;
    }
    public String getTipoPista() {
        return this.tipoPista;
    }
    
    public void setTipoPista(String tipoPista) {
        this.tipoPista = tipoPista;
    }
    public String getTracadoVia() {
        return this.tracadoVia;
    }
    
    public void setTracadoVia(String tracadoVia) {
        this.tracadoVia = tracadoVia;
    }
    public String getUsoSolo() {
        return this.usoSolo;
    }
    
    public void setUsoSolo(String usoSolo) {
        this.usoSolo = usoSolo;
    }




}


