package mapeamento1;
// Generated 25/06/2018 17:10:40 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Data generated by hbm2java
 */
public class Data  implements java.io.Serializable {


     private int id;
     private Acidente acidente;
     private String diaSemana;
     private Date dataAcidente;
     private Integer horario;

    public Data() {
    }

	
    public Data(int id) {
        this.id = id;
    }
    public Data(int id, Acidente acidente, String diaSemana, Date dataAcidente, Integer horario) {
       this.id = id;
       this.acidente = acidente;
       this.diaSemana = diaSemana;
       this.dataAcidente = dataAcidente;
       this.horario = horario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Acidente getAcidente() {
        return this.acidente;
    }
    
    public void setAcidente(Acidente acidente) {
        this.acidente = acidente;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public Date getDataAcidente() {
        return this.dataAcidente;
    }
    
    public void setDataAcidente(Date dataAcidente) {
        this.dataAcidente = dataAcidente;
    }
    public Integer getHorario() {
        return this.horario;
    }
    
    public void setHorario(Integer horario) {
        this.horario = horario;
    }




}


