package mapeamento1;
// Generated 25/06/2018 17:10:40 by Hibernate Tools 4.3.1



/**
 * Local generated by hbm2java
 */
public class Local  implements java.io.Serializable {


     private int id;
     private Acidente acidente;
     private String uf;
     private Integer br;
     private String km;
     private String municipio;

    public Local() {
    }

	
    public Local(int id) {
        this.id = id;
    }
    public Local(int id, Acidente acidente, String uf, Integer br, String km, String municipio) {
       this.id = id;
       this.acidente = acidente;
       this.uf = uf;
       this.br = br;
       this.km = km;
       this.municipio = municipio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Acidente getAcidente() {
        return this.acidente;
    }
    
    public void setAcidente(Acidente acidente) {
        this.acidente = acidente;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public Integer getBr() {
        return this.br;
    }
    
    public void setBr(Integer br) {
        this.br = br;
    }
    public String getKm() {
        return this.km;
    }
    
    public void setKm(String km) {
        this.km = km;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }




}


