package mapeamento1;
// Generated 25/06/2018 17:10:40 by Hibernate Tools 4.3.1



/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String tmucodigo;
     private String tmuuf;
     private String tmudenominacao;

    public Municipio() {
    }

	
    public Municipio(String tmucodigo) {
        this.tmucodigo = tmucodigo;
    }
    public Municipio(String tmucodigo, String tmuuf, String tmudenominacao) {
       this.tmucodigo = tmucodigo;
       this.tmuuf = tmuuf;
       this.tmudenominacao = tmudenominacao;
    }
   
    public String getTmucodigo() {
        return this.tmucodigo;
    }
    
    public void setTmucodigo(String tmucodigo) {
        this.tmucodigo = tmucodigo;
    }
    public String getTmuuf() {
        return this.tmuuf;
    }
    
    public void setTmuuf(String tmuuf) {
        this.tmuuf = tmuuf;
    }
    public String getTmudenominacao() {
        return this.tmudenominacao;
    }
    
    public void setTmudenominacao(String tmudenominacao) {
        this.tmudenominacao = tmudenominacao;
    }




}


