package mapeamento1;
// Generated 25/06/2018 17:10:40 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private String senha;
     private String funcao;

    public Usuario() {
    }

	
    public Usuario(int codigo) {
        this.codigo = codigo;
    }
    public Usuario(int codigo, String nome, String senha, String funcao) {
       this.codigo = codigo;
       this.nome = nome;
       this.senha = senha;
       this.funcao = funcao;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }




}


